import Head from "next/head";
import { useCallback } from "react";
import { WalletConnect } from "../component/WalletConnect";
import { useMintNFT } from "../hook/MintNFT";

export default function Home() {
  const { send } = useMintNFT();
  const handleSubmit = async () => {
    await send("3rd", "10,000", "2022/11/21");
  };
  return (
    <div>
      <Head>
        <title>Scroll game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-full shadow-sm shadow-black/30">
        <div className="max-w-6xl mx-auto h-[70px] px-5 flex justify-between items-center">
          <h1 className="text-transparent font-extrabold text-2xl bg-clip-text bg-gradient-to-r from-[#4158D0] via-[#C850C0] to-[#FFCC70]">
            Kyutech hackathon
          </h1>
          <WalletConnect />
        </div>
      </header>
      <main className="w-full max-w-6xl mx-auto flex mt-20">
        <div className="w-[75%]">
          <div className="w-full h-[600px] bg-black"></div>
        </div>
        <div className="w-[25%] px-3">
          <h2 className="text-xl font-bold text-center">Ranking</h2>
          <ul>
            <li>1位 test</li>
            <li>2位 test</li>
            <li>3位 test</li>
          </ul>
          <button
            className="block mt-3 mx-auto text-sm leading-none cursor-pointer font-bold text-white bg-black py-4 px-5 rounded-md"
            onClick={handleSubmit}
          >
            Mint NFT
          </button>
        </div>
      </main>
    </div>
  );
}
