import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Scroll game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-full shadow-sm shadow-black/30">
        <div className="max-w-6xl mx-auto h-[70px] px-5 flex justify-between items-center">
          <h1 className="text-transparent font-extrabold text-2xl bg-clip-text bg-gradient-to-r from-[#4158D0] via-[#C850C0] to-[#FFCC70]">
            Kyutech hackathon
          </h1>
          <div className="flex items-center">
            <a
              href="https://github.com/kyutech-hackathon-b/scroll-game-client"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                alt="githubのロゴ"
                src="/logo-github.png"
                width={25}
                height={25}
              />
            </a>
            <button className="leading-none cursor-pointer font-bold text-white bg-black p-4 ml-8 rounded-md">
              Connect wallet
            </button>
          </div>
        </div>
      </header>
      <main className="w-full max-w-6xl mx-auto flex mt-20">
        <div className="w-[75%]">
          <div className="w-full h-[600px] bg-black"></div>
        </div>
        <div className="w-[25%] px-3">
          <h2 className="text-xl font-bold text-center">Ranking</h2>
          <ul>
            <li>1位 test</li>
            <li>2位 test</li>
            <li>3位 test</li>
          </ul>
        </div>
      </main>
    </div>
  );
}
